### ISSUE TITLE
ShowOrderDetails requires authentication

### ISSUE THREAD

**Issue by dlobato** [Sylius/ShopApiPlugin#428]
We are implementing checkout as a guest user and we realized that ShowOrderDetails endpoint (/{channelCode}/orders/{tokenValue} get) requires authentication, therefore after complete as a guest there is no way to access order details. But, using the carts endpoint (/{channelCode}/carts/{token} get) we can access to the placed order information anyway (it doesn't check if order is on cart state).

The question is: is it really needed to authenticate on the order details endpoint? if so, how do you suggest to implement this for guest users?

**Comment by lchrusciel** [comment]
I would say, that cart endpoint should care only about orders in cart state. 

And according to order endpoint, it should allow accessing guest orders, while checking authorization for carts placed by users with account.

**Comment by mamazu** [comment]
We have also noticed this issue that a guest can not access their order view. The problem with that is if you open the endpoint for guest carts to have no authentication, then you would also be able to see the orders of other guests without any authentication and this would be a huge problem because on the orders there is sensitive information like the address.
What I would suggest for guest checkouts would be: The customer gets an order confirmation mail anyways so why not include some kind of token so that for guest orders the user has to also provide a token to view the order summary.

And for the cart... it's still under development. :D

**Comment by dlobato** [comment]
The order token is already a random hash, so it is not like you can access an order by randomly trying.
We need to access the order detail right after complete, to show the order number or to allow changing payment method in case of error, so the email solution wouldn't be ideal in our use case.

**Comment by mamazu** [comment]
Hm, so the currently best solution to get the order number of an order on the cart complete endpoint is just to override or decorate the endpoint and then after the order is created query the database for the most recent order. This is not the most beautiful solution but this is the way to do it as the command that creates the order can/should not return the order (or it's number).

**Comment by dlobato** [comment]
Well, I understand I can override the endpoint to do whatever fits my requirements, but I'd rather use standard behavior and that's why I'm discussing the subject here.

/{channelCode}/carts/{token} get allows you to access any order (regardless of order state) information given that you have the right token. So, it seems clear that this is not the intended behavior and it should be marked as a bug (carts endpoint should check order is in cart state).

On the other hand, I still believe that /{channelCode}/orders/{tokenValue} get endpoint authentication is not needed as tokenValue can't be randomly guessed and therefore only the client that created the order have access to it. I might be wrong, could you give me a good reason to change my mind?

**Comment by mamazu** [comment]
What kind of information should the complete order endpoint return? We implemented it such that the endpoint only returns the order number. Do you think this would be sufficient or would the whole order view be better?

The second point you mentioned about the cart endpoint is a bug in my opinion and needs to be fixed.

And about the authorized order endpoint. I don't have any argument why it feels saver if it just works with authorization but technically yes a token can not really be guessed.

**Comment by dlobato** [comment]
It is not just about complete (which currently returns nothing), but also about changing payment after payment failure or getting the order information from a link sent by email.
I've checked the implementation on the ShopBundle and I could access any order by it's token at: /order/{token} so ShopApi offers a different behavior here.

My only concern about droping authentication is that then you can't ensure who has access to the information, which I agree is sensitive. But on the other hand, how would a potential attacker forge an order token? The only way I see it's if he already has access to the customer computer and then it doesn't matter what we do, he already has all required credentials.

**Comment by lchrusciel** [comment]
I will also add my two cents.

First of all, access to all orders on cart endpoint is a bug, should be fixed. On cart endpoint only not placed orders should be available. According to orders endpoint, I would say, that we should stick as close as possible with the default implementation. This means that we only present a minimal amount of data for guests:
![image](https://user-images.githubusercontent.com/6213903/56963028-40cd4800-6b58-11e9-859e-e8e7b5801082.png). More data is available when one creates an account.

In a perfect world, I would recommend to protect this endpoint and don't expose anything if an order has shop user assigned, otherwise list more data, but protect it with some pin maybe?

**Comment by dlobato** [comment]
I'll then create a separate issue for the bug report on cart endpoint.
And for your proposal, it seems like the best option so far. I'll open a PR with initial changes and we can work from there. Orders made by logged in users can be identified, and I'd also just forbid access to thos unless you are authenticated. For the rest, at least the minimum required to update payment, totals, order number, date, and maybe items.

**Comment by dlobato** [comment]
cart bug report: #438

**Comment by diimpp** [comment]
Shouldn't be this issue closed? Both of the described issues seems to be solved in release candidate. /cc @dlobato

**Comment by dlobato** [comment]
Sure, I'll just close it then.
