### ISSUE TITLE
Unable to apply serialization groups

### ISSUE THREAD

**Issue by kayue** [Sylius/ShopApiPlugin#610]
## The Problem

JMSSerializerBundle allows developers to use serialization groups and versions to control property visibility.

ShopApiPlugin default doesn't have any serialization groups applied. In Sylius (or SyliusResourceBundle), developers can control serialization via `RequestConfigurationFactory`. However, ShopApiPlugin doesn't use it at all, and it is not possible to override FosRestBundle's `ViewHandler` due to [restriction in Sylius bundle](https://github.com/Sylius/SyliusResourceBundle/pull/120/files).

## Solution

In the long term, I think Sylius should have a unified way to control serialization. 
A quick solution would allow developer to override FosRestBundle's `ViewHandler` like what I proposed in https://github.com/Sylius/SyliusResourceBundle/pull/120

**Comment by mamazu** [comment]
In my opinion there are two different problems. The first is the one you described but the fact of the matter is that in shop api we don't really use the resource bundle very much. And for routes like the `Cart\SummarizeAction` you can inject your own ViewHandler as you see fit. So the problem is limited (in the Shop API) to the address book routes. But as far as I know you can just replace the Sylius ViewHandler all together?

**Comment by kayue** [comment]
If I can extend `fos_rest.view_handler` then I might be able to do what I want, but it is not possible to replace `fos_rest.view_handler` until https://github.com/Sylius/SyliusResourceBundle/pull/120 is merged and released.

**Comment by mamazu** [comment]
As far as I can tell this should now be possible since the SyliusResourceBundle now uses the `ConfigurableViewHandlerInterface` as typehint.
