### ISSUE TITLE
Incorrect product variants documentation

### ISSUE THREAD

**Issue by josgerrits** [Sylius/ShopApiPlugin#641]
Hey everyone,

The documentation states that when retrieving the a cart /carts/{token} should return the variants with the variant code as the key of the array. This is not happening and the key is the index of the array.

**Comment by mamazu** [comment]
You are right. This is an error in the documentation. I would suggest changing the documentation as changing the behavior is not really an option.

The reason this was documented that way is because there are different ways to serialize a product in the ShopApi and one of them is doing it with an associative array. (\Sylius\ShopApiPlugin\Factory\Product\ListProductViewFactory)

**Comment by mamazu** [comment]
Also another thing to note here is that the product variant list of the product on the cart only shows the variant the user put into the cart.
